React Styling: CSS, Styled Components, SVG
Victoria240/react-todo pull request #16
Opened 2023-09-05 21:16 UTC by Victoria240

2023-09-05 21:27 UTC, Victoria240 commented
I'm not sure what the base branch should be - main or 1.9. Is there a factor that determines what option to choose?

2023-09-08 23:04 UTC, dargaCode requested changes
Great use of flexbox, Victoria!

I don't think this PR is meeting the requirements for being responsive yet though. Please add some more styling inside of your media queries, and in particular see if you can change the layout aspects as the page gets narrower, so all the elements will still fit on the page 📈

2023-09-08 23:04 UTC, dargaCode commented on src/App.module.css
> +    }
It's a little unusual to make all the headings the same font size, since usually they're meant to indicate a "hierarchy" of important information. I can see you only use the `h2` on the `/new` page, and it replaces the original `h1` heading. I think in this case you could just style the `h1` heading and use it on both the main page and `/new`

2023-09-08 23:04 UTC, dargaCode commented on src/App.module.css
> +    background: #061C3D;
this is a small nit but officially when we're setting a background color, we should use `background-color` instead of `background` (which can also include image or other more complicated stuff)

2023-09-08 23:04 UTC, dargaCode commented on src/App.module.css
> +    }
I don't think there's enough happening here to fulfill the Media Queries part of the assignment. See if you can try to change the styling of some of your containers to make sure all the items fit on the screen as the width gets narrower.

2023-09-08 23:04 UTC, dargaCode commented on src/Checkbox.module.css
> +/* Checkbox.module.css */
Not sure if this is on purpose but this file doesn't seem to be connected to the actual component. If you've temporarily disabled it that makes total sense just checking

2023-09-08 23:04 UTC, dargaCode commented on src/TodoListItem.module.css
> +.ListItem::before {
very nice! it could be easier and get a similar result to use the `border-left` property on the list item itself

2023-09-10 18:14 UTC, closed without merging